set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $APP_DB_USER WITH PASSWORD '$APP_DB_PASSWORD';
    CREATE USER $KC_DB_USER WITH PASSWORD '$KC_DB_PASSWORD';

    CREATE DATABASE $APP_DB_NAME;
    CREATE DATABASE $KC_DB_NAME;

    REVOKE ALL ON DATABASE $APP_DB_NAME FROM PUBLIC;
    REVOKE ALL ON DATABASE $KC_DB_NAME FROM PUBLIC;

    GRANT CONNECT, CREATE, TEMPORARY ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_USER;
    REVOKE ALL ON DATABASE $APP_DB_NAME FROM $KC_DB_USER;

    GRANT CONNECT, CREATE, TEMPORARY ON DATABASE $KC_DB_NAME TO $KC_DB_USER;
    GRANT ALL PRIVILEGES ON DATABASE $KC_DB_NAME TO $KC_DB_USER;
    REVOKE ALL ON DATABASE $KC_DB_NAME FROM $APP_DB_USER;

    \c $APP_DB_NAME
    REVOKE ALL ON SCHEMA public FROM PUBLIC;
    GRANT USAGE, CREATE ON SCHEMA public TO $APP_DB_USER;
    ALTER SCHEMA public OWNER TO $APP_DB_USER;

    \c $KC_DB_NAME
    REVOKE ALL ON SCHEMA public FROM PUBLIC;
    GRANT USAGE, CREATE ON SCHEMA public TO $KC_DB_USER;
    ALTER SCHEMA public OWNER TO $KC_DB_USER;
EOSQL